- name: ":robot: AutoSummon"
  color: "8A2BE2"
  description: "Bot-summoned chores: releases, bumps, and other scripted nonsense."

- name: ":question: Clue Me In"
  color: "007BFF"
  description: "Explain this to me like I haven't been staring at it for 3 hours."

- name: ":repeat: Déjà Vu"
  color: "4C6EF5"
  description: "We've seen this before. Link it, close it, keep moving."

- name: ":gem: Cracked Gem"
  color: "B56576"
  description: "Something's broken again and it's probably important."

- name: ":file_folder: Case File"
  color: "3FA7D6"
  description: "Forensics, repro steps, logs, and other missing clues."

- name: ":sparkles: Divine Intervention"
  color: "C678DD"
  description: "Feature requests, wish lists, and unlikely code miracles."

- name: ":large_green_circle: Red Light Green Light"
  color: "2ECC71"
  description: "Low risk, n00b-safe, and probably fine to merge."

- name: ":no_entry_sign: NopeNotHappening"
  color: "6C757D"
  description: "Won't fix. Not now, not later, not ever."

- name: ":bug: Invalidated"
  color: "FFC107"
  description: "Not a bug. Misread spec, haunted cache, or user gremlin."

- name: ":crystal_ball: Spirit Guide"
  color: "6F42C1"
  description: "Help from maintainers, mentors, or whoever knows this mess best."
